POST http://localhost:8080/cart
Content-Type: application/json
Accept-Language: sv

{
    "_id": "10",
    "name": "Nike Blazer Mid Suede",
    "imageUrl": "/img/sneakers/s10.png",
    "price": 1400
}


###
GET http://localhost:8080/sneakers


### DogId can be whatever
DELETE http://localhost:8080/cart/623c5599dbe160c6fb41cd0b



###
PATCH http://localhost:8080/sneakers/c
Content-Type: application/json

{

    "age": "2"
    
}

